name: Infrastructure

on:
  push:
    branches: [main]
    paths:
      - "terraform/**"
  workflow_dispatch:

env:
  AWS_REGION: us-west-2

jobs:
  terraform:
    name: Plan and Apply Infrastructure
    runs-on: ubuntu-latest

    env:
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_rails_master_key: ${{ secrets.RAILS_MASTER_KEY }}
      TF_VAR_secret_key_base: ${{ secrets.SECRET_KEY_BASE }}
      TF_VAR_devise_jwt_secret: ${{ secrets.DEVISE_JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
